"""Northwind default

Revision ID: a61276f4cd6d
Revises: 
Create Date: 2023-07-22 15:38:14.587457

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a61276f4cd6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_demographics')
    op.drop_table('us_states')
    op.drop_table('employee_territories')
    op.drop_table('territories')
    op.drop_table('customer_customer_demo')
    op.drop_constraint('fk_employees_employees', 'employees', type_='foreignkey')
    op.drop_constraint('fk_order_details_products', 'order_details', type_='foreignkey')
    op.drop_constraint('fk_order_details_orders', 'order_details', type_='foreignkey')
    op.create_foreign_key(None, 'order_details', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_details', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.alter_column('orders', 'customer_id',
                    existing_type=sa.NullType(),
                    nullable=False)
    op.alter_column('orders', 'employee_id',
                    existing_type=sa.SMALLINT(),
                    nullable=False)
    op.drop_constraint('fk_orders_employees', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_customers', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_shippers', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'employees', ['employee_id'], ['employee_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')
    op.drop_constraint('fk_products_categories', 'products', type_='foreignkey')
    op.drop_constraint('fk_products_suppliers', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['supplier_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_suppliers', 'products', 'suppliers', ['supplier_id'], ['supplier_id'])
    op.create_foreign_key('fk_products_categories', 'products', 'categories', ['category_id'], ['category_id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_shippers', 'orders', 'shippers', ['ship_via'], ['shipper_id'])
    op.create_foreign_key('fk_orders_customers', 'orders', 'customers', ['customer_id'], ['customer_id'])
    op.create_foreign_key('fk_orders_employees', 'orders', 'employees', ['employee_id'], ['employee_id'])
    op.alter_column('orders', 'employee_id',
                    existing_type=sa.SMALLINT(),
                    nullable=True)
    op.alter_column('orders', 'customer_id',
                    existing_type=sa.NullType(),
                    nullable=True)
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.create_foreign_key('fk_order_details_orders', 'order_details', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key('fk_order_details_products', 'order_details', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key('fk_employees_employees', 'employees', 'employees', ['reports_to'], ['employee_id'])
    op.create_table('customer_customer_demo',
                    sa.Column('customer_id', sa.NullType(), autoincrement=False, nullable=False),
                    sa.Column('customer_type_id', sa.NullType(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'],
                                            name='fk_customer_customer_demo_customers'),
                    sa.ForeignKeyConstraint(['customer_type_id'], ['customer_demographics.customer_type_id'],
                                            name='fk_customer_customer_demo_customer_demographics'),
                    sa.PrimaryKeyConstraint('customer_id', 'customer_type_id', name='pk_customer_customer_demo')
                    )
    op.create_table('territories',
                    sa.Column('territory_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
                    sa.Column('territory_description', sa.NullType(), autoincrement=False, nullable=False),
                    sa.Column('region_id', sa.SMALLINT(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], name='fk_territories_region'),
                    sa.PrimaryKeyConstraint('territory_id', name='pk_territories'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('employee_territories',
                    sa.Column('employee_id', sa.SMALLINT(), autoincrement=False, nullable=False),
                    sa.Column('territory_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'],
                                            name='fk_employee_territories_employees'),
                    sa.ForeignKeyConstraint(['territory_id'], ['territories.territory_id'],
                                            name='fk_employee_territories_territories'),
                    sa.PrimaryKeyConstraint('employee_id', 'territory_id', name='pk_employee_territories')
                    )
    op.create_table('us_states',
                    sa.Column('state_id', sa.SMALLINT(), autoincrement=False, nullable=False),
                    sa.Column('state_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
                    sa.Column('state_abbr', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
                    sa.Column('state_region', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('state_id', name='pk_usstates')
                    )
    op.create_table('customer_demographics',
                    sa.Column('customer_type_id', sa.NullType(), autoincrement=False, nullable=False),
                    sa.Column('customer_desc', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('customer_type_id', name='pk_customer_demographics')
                    )
    # ### end Alembic commands ###
